const Discord = require('discord.js');
const data_sys = require('../../data/structjson/all_systeme.json');
const { fun_sleep } = require('../Fun/fun_sleep');


async function send(message) {
    message.channel.send('!systeme_data_create');
}
async function fun_systeme_roles_create(message, command)
{
    let role_guilde;
    try{                                                                                                                                                                                                                                                




        


        role_guilde = await message.guild.roles.create({data: {name: data_sys.Likeur_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Likeur_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Likeur_or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Likeur_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Recruteur_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Recruteur_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Recruteur_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Recruteur_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Espion_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Espion_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Espion_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Espion_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Muse_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Muse_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Muse_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Muse_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Attaquant_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Attaquant_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Attaquant_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Attaquant_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Defenseur_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Defenseur_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Defenseur_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Defenseur_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Braconnier_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Braconnier_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Braconnier_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Braconnier_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Chercheur_de_Trésor_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Chercheur_de_Trésor_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Chercheur_de_Trésor_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Chercheur_de_Trésor_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Voleur_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Voleur_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Voleur_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Voleur_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Donateur_bronze_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Donateur_argent_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Donateur_Or_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        role_guilde = await message.guild.roles.create({data: {name: data_sys.Donateur_Platine_name , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');

        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_COALITION , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_TRESORIER , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_PROTECTEUR , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_NOMADE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_CHERCHEUR_DE_TRESOR , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_SECRETAIRE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_RECRUTEUR , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_TUEUR_DE_PERCEPTEUR , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_BRACONNIER , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_APPRENTIE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_PENITENT , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_BOULET , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_RESERVISTE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_ESPION , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_ESSAI , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
        await role_guilde.permissions.remove('VIEW_CHANNEL');
        fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_DESERTEUR , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_INITIE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_ARTISAN , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_MASCOTTE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_MEMBRE_NON_GUILDE , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_NOUVEAU , color: 'GOLD', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.RANG_MUSE , color: 'GOLD', hoist : true, mentionable: true, ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');   
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.STAFF , color: 'GOLD', hoist : true, mentionable: true, ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_1_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_2_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_3_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_4_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_5_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_6_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_7_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_8_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_9_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_10_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_11_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_12_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_13_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_14_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_15_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_16_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_17_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);
        role_guilde = await message.guild.roles.create({data: {name: data_sys.roles_tuto_18_name , color: 'WHITE', hoist : true, mentionable: true,  ADMINISTRATOR : false}, reason: 'Create '});
        fun_sleep(200);
            await role_guilde.permissions.remove('VIEW_CHANNEL');
            fun_sleep(200);

        message.channel.send("**Les rôles ont bien été créés. Chargement,...**")
        setTimeout(send, 5000, message);
    } catch (error) {
        console.error(error);
    }        
}
exports.fun_systeme_roles_create = fun_systeme_roles_create;